### ISSUE TITLE
Invert "mark as delivered"

### ISSUE THREAD

**Issue by qzio** [dulvie/emmy#257]
At least for one organization, the DEFAULT is to always deliver the product before making the invoice.

This means that remembering to click "delivered" is an extra step that is easily forgotten.

The system should rather ask "at what date was this product delivered" when making the invoice, and default to "today".
There must also be a button that says something like "The product have not been delivered yet"

**Comment by maxhansson** [comment]
The problem: Forget clicking delivered
When clicking prepared the invoice is created. The delivery is a separate status. 

Solutions:
1) When changing status to prepared also have a checkbox delivered (defalt to yes). Same date is set to prepared and delivered. Possible to uncheck checkbox and then no delivery is set.
2) Possible to set boh prepared date and date of delivery. Also have the ability to wait to put the date of delivery.
3) Another way to handle the problem is with messages to responsible for warehouse.  
4) Move the creation of invoice to status delivered.

**Comment by qzio** [comment]
I don't understand 4) and 2)
By 3) you mean to implement some kind of notification system to nag administrators that the invoice is not yet delivered?

I feel 1) is probably a good idea.

The question of "is this order already delivered?" should be asked when an admin "moves" the `Sale` into the state where the "pdf-invoice" is created.
and 1) would do that.
